### ISSUE TITLE
type issue in main.ts

### ISSUE THREAD

**Issue by baixiaoyu2997** [storybook-vue/nuxt#103]
### Issue

'docgen' does not exist in type 'FrameworkOptions'

![image](https://github.com/storybook-vue/storybook-nuxt/assets/9149999/47520f26-3324-4d2f-af17-6d051fa1cfaf)

### Reference
https://github.com/storybook-vue/storybook-nuxt/edit/main/packages/storybook-nuxt/src/types.d.ts

https://github.com/storybookjs/storybook/blob/7b2ddea221a8eac43eb45a738d2408e7ef072a16/code/frameworks/vue3-vite/src/types.ts#L24

**Comment by RodriguezTheo** [comment]
Not only, 
The plugin use @storybook/vue3 but need @storybook/vue3-vite...

**Comment by tobiasdiez** [comment]
Static dirs might also have a problem as mentioned in https://github.com/nuxt-modules/storybook/issues/574.
